// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Site is the predicate function for site builders.
type Site func(*sql.Selector)
