version: '3'
services:
  rss-generator:
    platform: linux/x86_64
    build:
      dockerfile: ./docker/rss-generator/Dockerfile
      context: .
      target: development
    env_file: ./rss-generator/.env
    volumes:
      - ./rss-generator:/usr/local/src/rss-generator
    ports:
      - "8080:80"
      - "2345:2345"
    environment:
      TZ: "Asia/Tokyo"
      PORT: "80"
      DATABASE_USER: "user"
      DATABASE_PASSWORD: "password"
      DATABASE_HOST: "mysql"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "rss"
      SELENIUM_SERVER_URL: "http://selenium:4444/wd/hub"
    depends_on:
      - selenium
      - mysql

  selenium:
    image: selenium/standalone-chrome:123.0.6312.86-chromedriver-123.0.6312.86-grid-4.19.1-20240402
    ports:
      - "4444:4444"
    shm_size: "2g"

  mysql:
    platform: linux/x86_64
    build:
      dockerfile: ./docker/mysql/Dockerfile
      context: .
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "rss"
      TZ: "Asia/Tokyo"
    ports:
      - "13306:3306"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql

volumes:
  mysql:
    driver: local
