// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ITK13201/rss-generator/ent/schema"
	"github.com/ITK13201/rss-generator/ent/scrapingselector"
	"github.com/ITK13201/rss-generator/ent/site"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	scrapingselectorFields := schema.ScrapingSelector{}.Fields()
	_ = scrapingselectorFields
	// scrapingselectorDescSelector is the schema descriptor for selector field.
	scrapingselectorDescSelector := scrapingselectorFields[1].Descriptor()
	// scrapingselector.SelectorValidator is a validator for the "selector" field. It is called by the builders before save.
	scrapingselector.SelectorValidator = scrapingselectorDescSelector.Validators[0].(func(string) error)
	// scrapingselectorDescInnerSelector is the schema descriptor for inner_selector field.
	scrapingselectorDescInnerSelector := scrapingselectorFields[2].Descriptor()
	// scrapingselector.InnerSelectorValidator is a validator for the "inner_selector" field. It is called by the builders before save.
	scrapingselector.InnerSelectorValidator = scrapingselectorDescInnerSelector.Validators[0].(func(string) error)
	// scrapingselectorDescTitleSelector is the schema descriptor for title_selector field.
	scrapingselectorDescTitleSelector := scrapingselectorFields[3].Descriptor()
	// scrapingselector.TitleSelectorValidator is a validator for the "title_selector" field. It is called by the builders before save.
	scrapingselector.TitleSelectorValidator = scrapingselectorDescTitleSelector.Validators[0].(func(string) error)
	// scrapingselectorDescCreatedAt is the schema descriptor for created_at field.
	scrapingselectorDescCreatedAt := scrapingselectorFields[6].Descriptor()
	// scrapingselector.DefaultCreatedAt holds the default value on creation for the created_at field.
	scrapingselector.DefaultCreatedAt = scrapingselectorDescCreatedAt.Default.(func() time.Time)
	// scrapingselectorDescUpdatedAt is the schema descriptor for updated_at field.
	scrapingselectorDescUpdatedAt := scrapingselectorFields[7].Descriptor()
	// scrapingselector.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	scrapingselector.DefaultUpdatedAt = scrapingselectorDescUpdatedAt.Default.(func() time.Time)
	// scrapingselector.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	scrapingselector.UpdateDefaultUpdatedAt = scrapingselectorDescUpdatedAt.UpdateDefault.(func() time.Time)
	siteFields := schema.Site{}.Fields()
	_ = siteFields
	// siteDescSlug is the schema descriptor for slug field.
	siteDescSlug := siteFields[1].Descriptor()
	// site.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	site.SlugValidator = siteDescSlug.Validators[0].(func(string) error)
	// siteDescTitle is the schema descriptor for title field.
	siteDescTitle := siteFields[2].Descriptor()
	// site.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	site.TitleValidator = siteDescTitle.Validators[0].(func(string) error)
	// siteDescURL is the schema descriptor for url field.
	siteDescURL := siteFields[4].Descriptor()
	// site.URLValidator is a validator for the "url" field. It is called by the builders before save.
	site.URLValidator = siteDescURL.Validators[0].(func(string) error)
	// siteDescEnableJsRendering is the schema descriptor for enable_js_rendering field.
	siteDescEnableJsRendering := siteFields[5].Descriptor()
	// site.DefaultEnableJsRendering holds the default value on creation for the enable_js_rendering field.
	site.DefaultEnableJsRendering = siteDescEnableJsRendering.Default.(bool)
	// siteDescCreatedAt is the schema descriptor for created_at field.
	siteDescCreatedAt := siteFields[6].Descriptor()
	// site.DefaultCreatedAt holds the default value on creation for the created_at field.
	site.DefaultCreatedAt = siteDescCreatedAt.Default.(func() time.Time)
	// siteDescUpdatedAt is the schema descriptor for updated_at field.
	siteDescUpdatedAt := siteFields[7].Descriptor()
	// site.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	site.DefaultUpdatedAt = siteDescUpdatedAt.Default.(func() time.Time)
	// site.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	site.UpdateDefaultUpdatedAt = siteDescUpdatedAt.UpdateDefault.(func() time.Time)
}
