// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ITK13201/rss-generator/ent/feed"
	"github.com/ITK13201/rss-generator/ent/feeditem"
	"github.com/ITK13201/rss-generator/ent/schema"
	"github.com/ITK13201/rss-generator/ent/scrapingsetting"
	"github.com/ITK13201/rss-generator/ent/site"
	"github.com/ITK13201/rss-generator/ent/testfeed"
	"github.com/ITK13201/rss-generator/ent/testfeeditem"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	feedFields := schema.Feed{}.Fields()
	_ = feedFields
	// feedDescTitle is the schema descriptor for title field.
	feedDescTitle := feedFields[1].Descriptor()
	// feed.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	feed.TitleValidator = feedDescTitle.Validators[0].(func(string) error)
	// feedDescDescription is the schema descriptor for description field.
	feedDescDescription := feedFields[2].Descriptor()
	// feed.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	feed.DescriptionValidator = feedDescDescription.Validators[0].(func(string) error)
	// feedDescLink is the schema descriptor for link field.
	feedDescLink := feedFields[3].Descriptor()
	// feed.LinkValidator is a validator for the "link" field. It is called by the builders before save.
	feed.LinkValidator = feedDescLink.Validators[0].(func(string) error)
	// feedDescCreatedAt is the schema descriptor for created_at field.
	feedDescCreatedAt := feedFields[5].Descriptor()
	// feed.DefaultCreatedAt holds the default value on creation for the created_at field.
	feed.DefaultCreatedAt = feedDescCreatedAt.Default.(func() time.Time)
	// feedDescUpdatedAt is the schema descriptor for updated_at field.
	feedDescUpdatedAt := feedFields[6].Descriptor()
	// feed.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	feed.DefaultUpdatedAt = feedDescUpdatedAt.Default.(func() time.Time)
	// feed.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	feed.UpdateDefaultUpdatedAt = feedDescUpdatedAt.UpdateDefault.(func() time.Time)
	// feedDescID is the schema descriptor for id field.
	feedDescID := feedFields[0].Descriptor()
	// feed.DefaultID holds the default value on creation for the id field.
	feed.DefaultID = feedDescID.Default.(func() uuid.UUID)
	feeditemFields := schema.FeedItem{}.Fields()
	_ = feeditemFields
	// feeditemDescTitle is the schema descriptor for title field.
	feeditemDescTitle := feeditemFields[1].Descriptor()
	// feeditem.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	feeditem.TitleValidator = feeditemDescTitle.Validators[0].(func(string) error)
	// feeditemDescDescription is the schema descriptor for description field.
	feeditemDescDescription := feeditemFields[2].Descriptor()
	// feeditem.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	feeditem.DescriptionValidator = feeditemDescDescription.Validators[0].(func(string) error)
	// feeditemDescCreatedAt is the schema descriptor for created_at field.
	feeditemDescCreatedAt := feeditemFields[5].Descriptor()
	// feeditem.DefaultCreatedAt holds the default value on creation for the created_at field.
	feeditem.DefaultCreatedAt = feeditemDescCreatedAt.Default.(func() time.Time)
	// feeditemDescUpdatedAt is the schema descriptor for updated_at field.
	feeditemDescUpdatedAt := feeditemFields[6].Descriptor()
	// feeditem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	feeditem.DefaultUpdatedAt = feeditemDescUpdatedAt.Default.(func() time.Time)
	// feeditem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	feeditem.UpdateDefaultUpdatedAt = feeditemDescUpdatedAt.UpdateDefault.(func() time.Time)
	scrapingsettingFields := schema.ScrapingSetting{}.Fields()
	_ = scrapingsettingFields
	// scrapingsettingDescSelector is the schema descriptor for selector field.
	scrapingsettingDescSelector := scrapingsettingFields[1].Descriptor()
	// scrapingsetting.SelectorValidator is a validator for the "selector" field. It is called by the builders before save.
	scrapingsetting.SelectorValidator = scrapingsettingDescSelector.Validators[0].(func(string) error)
	// scrapingsettingDescInnerSelector is the schema descriptor for inner_selector field.
	scrapingsettingDescInnerSelector := scrapingsettingFields[2].Descriptor()
	// scrapingsetting.InnerSelectorValidator is a validator for the "inner_selector" field. It is called by the builders before save.
	scrapingsetting.InnerSelectorValidator = scrapingsettingDescInnerSelector.Validators[0].(func(string) error)
	// scrapingsettingDescTitleSelector is the schema descriptor for title_selector field.
	scrapingsettingDescTitleSelector := scrapingsettingFields[3].Descriptor()
	// scrapingsetting.TitleSelectorValidator is a validator for the "title_selector" field. It is called by the builders before save.
	scrapingsetting.TitleSelectorValidator = scrapingsettingDescTitleSelector.Validators[0].(func(string) error)
	// scrapingsettingDescCreatedAt is the schema descriptor for created_at field.
	scrapingsettingDescCreatedAt := scrapingsettingFields[6].Descriptor()
	// scrapingsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	scrapingsetting.DefaultCreatedAt = scrapingsettingDescCreatedAt.Default.(func() time.Time)
	// scrapingsettingDescUpdatedAt is the schema descriptor for updated_at field.
	scrapingsettingDescUpdatedAt := scrapingsettingFields[7].Descriptor()
	// scrapingsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	scrapingsetting.DefaultUpdatedAt = scrapingsettingDescUpdatedAt.Default.(func() time.Time)
	// scrapingsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	scrapingsetting.UpdateDefaultUpdatedAt = scrapingsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	siteFields := schema.Site{}.Fields()
	_ = siteFields
	// siteDescSlug is the schema descriptor for slug field.
	siteDescSlug := siteFields[1].Descriptor()
	// site.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	site.SlugValidator = siteDescSlug.Validators[0].(func(string) error)
	// siteDescTitle is the schema descriptor for title field.
	siteDescTitle := siteFields[2].Descriptor()
	// site.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	site.TitleValidator = siteDescTitle.Validators[0].(func(string) error)
	// siteDescURL is the schema descriptor for url field.
	siteDescURL := siteFields[4].Descriptor()
	// site.URLValidator is a validator for the "url" field. It is called by the builders before save.
	site.URLValidator = siteDescURL.Validators[0].(func(string) error)
	// siteDescEnableJsRendering is the schema descriptor for enable_js_rendering field.
	siteDescEnableJsRendering := siteFields[5].Descriptor()
	// site.DefaultEnableJsRendering holds the default value on creation for the enable_js_rendering field.
	site.DefaultEnableJsRendering = siteDescEnableJsRendering.Default.(bool)
	// siteDescCreatedAt is the schema descriptor for created_at field.
	siteDescCreatedAt := siteFields[6].Descriptor()
	// site.DefaultCreatedAt holds the default value on creation for the created_at field.
	site.DefaultCreatedAt = siteDescCreatedAt.Default.(func() time.Time)
	// siteDescUpdatedAt is the schema descriptor for updated_at field.
	siteDescUpdatedAt := siteFields[7].Descriptor()
	// site.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	site.DefaultUpdatedAt = siteDescUpdatedAt.Default.(func() time.Time)
	// site.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	site.UpdateDefaultUpdatedAt = siteDescUpdatedAt.UpdateDefault.(func() time.Time)
	testfeedFields := schema.TestFeed{}.Fields()
	_ = testfeedFields
	// testfeedDescTitle is the schema descriptor for title field.
	testfeedDescTitle := testfeedFields[1].Descriptor()
	// testfeed.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	testfeed.TitleValidator = testfeedDescTitle.Validators[0].(func(string) error)
	// testfeedDescDescription is the schema descriptor for description field.
	testfeedDescDescription := testfeedFields[2].Descriptor()
	// testfeed.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	testfeed.DescriptionValidator = testfeedDescDescription.Validators[0].(func(string) error)
	// testfeedDescLink is the schema descriptor for link field.
	testfeedDescLink := testfeedFields[3].Descriptor()
	// testfeed.LinkValidator is a validator for the "link" field. It is called by the builders before save.
	testfeed.LinkValidator = testfeedDescLink.Validators[0].(func(string) error)
	// testfeedDescCreatedAt is the schema descriptor for created_at field.
	testfeedDescCreatedAt := testfeedFields[5].Descriptor()
	// testfeed.DefaultCreatedAt holds the default value on creation for the created_at field.
	testfeed.DefaultCreatedAt = testfeedDescCreatedAt.Default.(func() time.Time)
	// testfeedDescUpdatedAt is the schema descriptor for updated_at field.
	testfeedDescUpdatedAt := testfeedFields[6].Descriptor()
	// testfeed.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	testfeed.DefaultUpdatedAt = testfeedDescUpdatedAt.Default.(func() time.Time)
	// testfeed.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	testfeed.UpdateDefaultUpdatedAt = testfeedDescUpdatedAt.UpdateDefault.(func() time.Time)
	// testfeedDescID is the schema descriptor for id field.
	testfeedDescID := testfeedFields[0].Descriptor()
	// testfeed.DefaultID holds the default value on creation for the id field.
	testfeed.DefaultID = testfeedDescID.Default.(func() uuid.UUID)
	testfeeditemFields := schema.TestFeedItem{}.Fields()
	_ = testfeeditemFields
	// testfeeditemDescTitle is the schema descriptor for title field.
	testfeeditemDescTitle := testfeeditemFields[1].Descriptor()
	// testfeeditem.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	testfeeditem.TitleValidator = testfeeditemDescTitle.Validators[0].(func(string) error)
	// testfeeditemDescDescription is the schema descriptor for description field.
	testfeeditemDescDescription := testfeeditemFields[2].Descriptor()
	// testfeeditem.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	testfeeditem.DescriptionValidator = testfeeditemDescDescription.Validators[0].(func(string) error)
	// testfeeditemDescCreatedAt is the schema descriptor for created_at field.
	testfeeditemDescCreatedAt := testfeeditemFields[5].Descriptor()
	// testfeeditem.DefaultCreatedAt holds the default value on creation for the created_at field.
	testfeeditem.DefaultCreatedAt = testfeeditemDescCreatedAt.Default.(func() time.Time)
	// testfeeditemDescUpdatedAt is the schema descriptor for updated_at field.
	testfeeditemDescUpdatedAt := testfeeditemFields[6].Descriptor()
	// testfeeditem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	testfeeditem.DefaultUpdatedAt = testfeeditemDescUpdatedAt.Default.(func() time.Time)
	// testfeeditem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	testfeeditem.UpdateDefaultUpdatedAt = testfeeditemDescUpdatedAt.UpdateDefault.(func() time.Time)
}
