// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ITK13201/rss-generator/ent/predicate"
	"github.com/ITK13201/rss-generator/ent/scrapingsetting"
	"github.com/ITK13201/rss-generator/ent/site"
)

// ScrapingSettingQuery is the builder for querying ScrapingSetting entities.
type ScrapingSettingQuery struct {
	config
	ctx        *QueryContext
	order      []scrapingsetting.OrderOption
	inters     []Interceptor
	predicates []predicate.ScrapingSetting
	withSite   *SiteQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ScrapingSettingQuery builder.
func (ssq *ScrapingSettingQuery) Where(ps ...predicate.ScrapingSetting) *ScrapingSettingQuery {
	ssq.predicates = append(ssq.predicates, ps...)
	return ssq
}

// Limit the number of records to be returned by this query.
func (ssq *ScrapingSettingQuery) Limit(limit int) *ScrapingSettingQuery {
	ssq.ctx.Limit = &limit
	return ssq
}

// Offset to start from.
func (ssq *ScrapingSettingQuery) Offset(offset int) *ScrapingSettingQuery {
	ssq.ctx.Offset = &offset
	return ssq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ssq *ScrapingSettingQuery) Unique(unique bool) *ScrapingSettingQuery {
	ssq.ctx.Unique = &unique
	return ssq
}

// Order specifies how the records should be ordered.
func (ssq *ScrapingSettingQuery) Order(o ...scrapingsetting.OrderOption) *ScrapingSettingQuery {
	ssq.order = append(ssq.order, o...)
	return ssq
}

// QuerySite chains the current query on the "site" edge.
func (ssq *ScrapingSettingQuery) QuerySite() *SiteQuery {
	query := (&SiteClient{config: ssq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scrapingsetting.Table, scrapingsetting.FieldID, selector),
			sqlgraph.To(site.Table, site.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, scrapingsetting.SiteTable, scrapingsetting.SiteColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ScrapingSetting entity from the query.
// Returns a *NotFoundError when no ScrapingSetting was found.
func (ssq *ScrapingSettingQuery) First(ctx context.Context) (*ScrapingSetting, error) {
	nodes, err := ssq.Limit(1).All(setContextOp(ctx, ssq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{scrapingsetting.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ssq *ScrapingSettingQuery) FirstX(ctx context.Context) *ScrapingSetting {
	node, err := ssq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ScrapingSetting ID from the query.
// Returns a *NotFoundError when no ScrapingSetting ID was found.
func (ssq *ScrapingSettingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(1).IDs(setContextOp(ctx, ssq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{scrapingsetting.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ssq *ScrapingSettingQuery) FirstIDX(ctx context.Context) int {
	id, err := ssq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ScrapingSetting entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ScrapingSetting entity is found.
// Returns a *NotFoundError when no ScrapingSetting entities are found.
func (ssq *ScrapingSettingQuery) Only(ctx context.Context) (*ScrapingSetting, error) {
	nodes, err := ssq.Limit(2).All(setContextOp(ctx, ssq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{scrapingsetting.Label}
	default:
		return nil, &NotSingularError{scrapingsetting.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ssq *ScrapingSettingQuery) OnlyX(ctx context.Context) *ScrapingSetting {
	node, err := ssq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ScrapingSetting ID in the query.
// Returns a *NotSingularError when more than one ScrapingSetting ID is found.
// Returns a *NotFoundError when no entities are found.
func (ssq *ScrapingSettingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(2).IDs(setContextOp(ctx, ssq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{scrapingsetting.Label}
	default:
		err = &NotSingularError{scrapingsetting.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ssq *ScrapingSettingQuery) OnlyIDX(ctx context.Context) int {
	id, err := ssq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ScrapingSettings.
func (ssq *ScrapingSettingQuery) All(ctx context.Context) ([]*ScrapingSetting, error) {
	ctx = setContextOp(ctx, ssq.ctx, "All")
	if err := ssq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ScrapingSetting, *ScrapingSettingQuery]()
	return withInterceptors[[]*ScrapingSetting](ctx, ssq, qr, ssq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ssq *ScrapingSettingQuery) AllX(ctx context.Context) []*ScrapingSetting {
	nodes, err := ssq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ScrapingSetting IDs.
func (ssq *ScrapingSettingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ssq.ctx.Unique == nil && ssq.path != nil {
		ssq.Unique(true)
	}
	ctx = setContextOp(ctx, ssq.ctx, "IDs")
	if err = ssq.Select(scrapingsetting.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ssq *ScrapingSettingQuery) IDsX(ctx context.Context) []int {
	ids, err := ssq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ssq *ScrapingSettingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Count")
	if err := ssq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ssq, querierCount[*ScrapingSettingQuery](), ssq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ssq *ScrapingSettingQuery) CountX(ctx context.Context) int {
	count, err := ssq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ssq *ScrapingSettingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Exist")
	switch _, err := ssq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ssq *ScrapingSettingQuery) ExistX(ctx context.Context) bool {
	exist, err := ssq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ScrapingSettingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ssq *ScrapingSettingQuery) Clone() *ScrapingSettingQuery {
	if ssq == nil {
		return nil
	}
	return &ScrapingSettingQuery{
		config:     ssq.config,
		ctx:        ssq.ctx.Clone(),
		order:      append([]scrapingsetting.OrderOption{}, ssq.order...),
		inters:     append([]Interceptor{}, ssq.inters...),
		predicates: append([]predicate.ScrapingSetting{}, ssq.predicates...),
		withSite:   ssq.withSite.Clone(),
		// clone intermediate query.
		sql:  ssq.sql.Clone(),
		path: ssq.path,
	}
}

// WithSite tells the query-builder to eager-load the nodes that are connected to
// the "site" edge. The optional arguments are used to configure the query builder of the edge.
func (ssq *ScrapingSettingQuery) WithSite(opts ...func(*SiteQuery)) *ScrapingSettingQuery {
	query := (&SiteClient{config: ssq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssq.withSite = query
	return ssq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Selector string `json:"selector,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ScrapingSetting.Query().
//		GroupBy(scrapingsetting.FieldSelector).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ssq *ScrapingSettingQuery) GroupBy(field string, fields ...string) *ScrapingSettingGroupBy {
	ssq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ScrapingSettingGroupBy{build: ssq}
	grbuild.flds = &ssq.ctx.Fields
	grbuild.label = scrapingsetting.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Selector string `json:"selector,omitempty"`
//	}
//
//	client.ScrapingSetting.Query().
//		Select(scrapingsetting.FieldSelector).
//		Scan(ctx, &v)
func (ssq *ScrapingSettingQuery) Select(fields ...string) *ScrapingSettingSelect {
	ssq.ctx.Fields = append(ssq.ctx.Fields, fields...)
	sbuild := &ScrapingSettingSelect{ScrapingSettingQuery: ssq}
	sbuild.label = scrapingsetting.Label
	sbuild.flds, sbuild.scan = &ssq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ScrapingSettingSelect configured with the given aggregations.
func (ssq *ScrapingSettingQuery) Aggregate(fns ...AggregateFunc) *ScrapingSettingSelect {
	return ssq.Select().Aggregate(fns...)
}

func (ssq *ScrapingSettingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ssq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ssq); err != nil {
				return err
			}
		}
	}
	for _, f := range ssq.ctx.Fields {
		if !scrapingsetting.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ssq.path != nil {
		prev, err := ssq.path(ctx)
		if err != nil {
			return err
		}
		ssq.sql = prev
	}
	return nil
}

func (ssq *ScrapingSettingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ScrapingSetting, error) {
	var (
		nodes       = []*ScrapingSetting{}
		withFKs     = ssq.withFKs
		_spec       = ssq.querySpec()
		loadedTypes = [1]bool{
			ssq.withSite != nil,
		}
	)
	if ssq.withSite != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, scrapingsetting.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ScrapingSetting).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ScrapingSetting{config: ssq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ssq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ssq.withSite; query != nil {
		if err := ssq.loadSite(ctx, query, nodes, nil,
			func(n *ScrapingSetting, e *Site) { n.Edges.Site = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ssq *ScrapingSettingQuery) loadSite(ctx context.Context, query *SiteQuery, nodes []*ScrapingSetting, init func(*ScrapingSetting), assign func(*ScrapingSetting, *Site)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ScrapingSetting)
	for i := range nodes {
		if nodes[i].site_id == nil {
			continue
		}
		fk := *nodes[i].site_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(site.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "site_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ssq *ScrapingSettingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ssq.querySpec()
	_spec.Node.Columns = ssq.ctx.Fields
	if len(ssq.ctx.Fields) > 0 {
		_spec.Unique = ssq.ctx.Unique != nil && *ssq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ssq.driver, _spec)
}

func (ssq *ScrapingSettingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(scrapingsetting.Table, scrapingsetting.Columns, sqlgraph.NewFieldSpec(scrapingsetting.FieldID, field.TypeInt))
	_spec.From = ssq.sql
	if unique := ssq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ssq.path != nil {
		_spec.Unique = true
	}
	if fields := ssq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scrapingsetting.FieldID)
		for i := range fields {
			if fields[i] != scrapingsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ssq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ssq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ssq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ssq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ssq *ScrapingSettingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ssq.driver.Dialect())
	t1 := builder.Table(scrapingsetting.Table)
	columns := ssq.ctx.Fields
	if len(columns) == 0 {
		columns = scrapingsetting.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ssq.sql != nil {
		selector = ssq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ssq.ctx.Unique != nil && *ssq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ssq.predicates {
		p(selector)
	}
	for _, p := range ssq.order {
		p(selector)
	}
	if offset := ssq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ssq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ScrapingSettingGroupBy is the group-by builder for ScrapingSetting entities.
type ScrapingSettingGroupBy struct {
	selector
	build *ScrapingSettingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ssgb *ScrapingSettingGroupBy) Aggregate(fns ...AggregateFunc) *ScrapingSettingGroupBy {
	ssgb.fns = append(ssgb.fns, fns...)
	return ssgb
}

// Scan applies the selector query and scans the result into the given value.
func (ssgb *ScrapingSettingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ssgb.build.ctx, "GroupBy")
	if err := ssgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScrapingSettingQuery, *ScrapingSettingGroupBy](ctx, ssgb.build, ssgb, ssgb.build.inters, v)
}

func (ssgb *ScrapingSettingGroupBy) sqlScan(ctx context.Context, root *ScrapingSettingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ssgb.fns))
	for _, fn := range ssgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ssgb.flds)+len(ssgb.fns))
		for _, f := range *ssgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ssgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ssgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ScrapingSettingSelect is the builder for selecting fields of ScrapingSetting entities.
type ScrapingSettingSelect struct {
	*ScrapingSettingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sss *ScrapingSettingSelect) Aggregate(fns ...AggregateFunc) *ScrapingSettingSelect {
	sss.fns = append(sss.fns, fns...)
	return sss
}

// Scan applies the selector query and scans the result into the given value.
func (sss *ScrapingSettingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sss.ctx, "Select")
	if err := sss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScrapingSettingQuery, *ScrapingSettingSelect](ctx, sss.ScrapingSettingQuery, sss, sss.inters, v)
}

func (sss *ScrapingSettingSelect) sqlScan(ctx context.Context, root *ScrapingSettingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sss.fns))
	for _, fn := range sss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
