// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ITK13201/rss-generator/ent/predicate"
	"github.com/ITK13201/rss-generator/ent/scrapingselector"
)

// ScrapingSelectorDelete is the builder for deleting a ScrapingSelector entity.
type ScrapingSelectorDelete struct {
	config
	hooks    []Hook
	mutation *ScrapingSelectorMutation
}

// Where appends a list predicates to the ScrapingSelectorDelete builder.
func (ssd *ScrapingSelectorDelete) Where(ps ...predicate.ScrapingSelector) *ScrapingSelectorDelete {
	ssd.mutation.Where(ps...)
	return ssd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ssd *ScrapingSelectorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ssd.sqlExec, ssd.mutation, ssd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ssd *ScrapingSelectorDelete) ExecX(ctx context.Context) int {
	n, err := ssd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ssd *ScrapingSelectorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(scrapingselector.Table, sqlgraph.NewFieldSpec(scrapingselector.FieldID, field.TypeInt))
	if ps := ssd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ssd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ssd.mutation.done = true
	return affected, err
}

// ScrapingSelectorDeleteOne is the builder for deleting a single ScrapingSelector entity.
type ScrapingSelectorDeleteOne struct {
	ssd *ScrapingSelectorDelete
}

// Where appends a list predicates to the ScrapingSelectorDelete builder.
func (ssdo *ScrapingSelectorDeleteOne) Where(ps ...predicate.ScrapingSelector) *ScrapingSelectorDeleteOne {
	ssdo.ssd.mutation.Where(ps...)
	return ssdo
}

// Exec executes the deletion query.
func (ssdo *ScrapingSelectorDeleteOne) Exec(ctx context.Context) error {
	n, err := ssdo.ssd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{scrapingselector.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ssdo *ScrapingSelectorDeleteOne) ExecX(ctx context.Context) {
	if err := ssdo.Exec(ctx); err != nil {
		panic(err)
	}
}
