// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ITK13201/rss-generator/ent/scrapingselector"
	"github.com/ITK13201/rss-generator/ent/site"
)

// ScrapingSelector is the model entity for the ScrapingSelector schema.
type ScrapingSelector struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Selector holds the value of the "selector" field.
	Selector string `json:"selector,omitempty"`
	// InnerSelector holds the value of the "inner_selector" field.
	InnerSelector string `json:"inner_selector,omitempty"`
	// TitleSelector holds the value of the "title_selector" field.
	TitleSelector string `json:"title_selector,omitempty"`
	// DescriptionSelector holds the value of the "description_selector" field.
	DescriptionSelector string `json:"description_selector,omitempty"`
	// LinkSelector holds the value of the "link_selector" field.
	LinkSelector string `json:"link_selector,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScrapingSelectorQuery when eager-loading is set.
	Edges        ScrapingSelectorEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ScrapingSelectorEdges holds the relations/edges for other nodes in the graph.
type ScrapingSelectorEdges struct {
	// Site holds the value of the site edge.
	Site *Site `json:"site,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SiteOrErr returns the Site value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScrapingSelectorEdges) SiteOrErr() (*Site, error) {
	if e.Site != nil {
		return e.Site, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: site.Label}
	}
	return nil, &NotLoadedError{edge: "site"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScrapingSelector) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scrapingselector.FieldID:
			values[i] = new(sql.NullInt64)
		case scrapingselector.FieldSelector, scrapingselector.FieldInnerSelector, scrapingselector.FieldTitleSelector, scrapingselector.FieldDescriptionSelector, scrapingselector.FieldLinkSelector:
			values[i] = new(sql.NullString)
		case scrapingselector.FieldCreatedAt, scrapingselector.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScrapingSelector fields.
func (ss *ScrapingSelector) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scrapingselector.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ss.ID = int(value.Int64)
		case scrapingselector.FieldSelector:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field selector", values[i])
			} else if value.Valid {
				ss.Selector = value.String
			}
		case scrapingselector.FieldInnerSelector:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field inner_selector", values[i])
			} else if value.Valid {
				ss.InnerSelector = value.String
			}
		case scrapingselector.FieldTitleSelector:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_selector", values[i])
			} else if value.Valid {
				ss.TitleSelector = value.String
			}
		case scrapingselector.FieldDescriptionSelector:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description_selector", values[i])
			} else if value.Valid {
				ss.DescriptionSelector = value.String
			}
		case scrapingselector.FieldLinkSelector:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link_selector", values[i])
			} else if value.Valid {
				ss.LinkSelector = value.String
			}
		case scrapingselector.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ss.CreatedAt = value.Time
			}
		case scrapingselector.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ss.UpdatedAt = value.Time
			}
		default:
			ss.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScrapingSelector.
// This includes values selected through modifiers, order, etc.
func (ss *ScrapingSelector) Value(name string) (ent.Value, error) {
	return ss.selectValues.Get(name)
}

// QuerySite queries the "site" edge of the ScrapingSelector entity.
func (ss *ScrapingSelector) QuerySite() *SiteQuery {
	return NewScrapingSelectorClient(ss.config).QuerySite(ss)
}

// Update returns a builder for updating this ScrapingSelector.
// Note that you need to call ScrapingSelector.Unwrap() before calling this method if this ScrapingSelector
// was returned from a transaction, and the transaction was committed or rolled back.
func (ss *ScrapingSelector) Update() *ScrapingSelectorUpdateOne {
	return NewScrapingSelectorClient(ss.config).UpdateOne(ss)
}

// Unwrap unwraps the ScrapingSelector entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ss *ScrapingSelector) Unwrap() *ScrapingSelector {
	_tx, ok := ss.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScrapingSelector is not a transactional entity")
	}
	ss.config.driver = _tx.drv
	return ss
}

// String implements the fmt.Stringer.
func (ss *ScrapingSelector) String() string {
	var builder strings.Builder
	builder.WriteString("ScrapingSelector(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ss.ID))
	builder.WriteString("selector=")
	builder.WriteString(ss.Selector)
	builder.WriteString(", ")
	builder.WriteString("inner_selector=")
	builder.WriteString(ss.InnerSelector)
	builder.WriteString(", ")
	builder.WriteString("title_selector=")
	builder.WriteString(ss.TitleSelector)
	builder.WriteString(", ")
	builder.WriteString("description_selector=")
	builder.WriteString(ss.DescriptionSelector)
	builder.WriteString(", ")
	builder.WriteString("link_selector=")
	builder.WriteString(ss.LinkSelector)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ss.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ss.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ScrapingSelectors is a parsable slice of ScrapingSelector.
type ScrapingSelectors []*ScrapingSelector
