// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ITK13201/rss-generator/ent/predicate"
	"github.com/ITK13201/rss-generator/ent/testfeed"
)

// TestFeedDelete is the builder for deleting a TestFeed entity.
type TestFeedDelete struct {
	config
	hooks    []Hook
	mutation *TestFeedMutation
}

// Where appends a list predicates to the TestFeedDelete builder.
func (tfd *TestFeedDelete) Where(ps ...predicate.TestFeed) *TestFeedDelete {
	tfd.mutation.Where(ps...)
	return tfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tfd *TestFeedDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tfd.sqlExec, tfd.mutation, tfd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tfd *TestFeedDelete) ExecX(ctx context.Context) int {
	n, err := tfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tfd *TestFeedDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(testfeed.Table, sqlgraph.NewFieldSpec(testfeed.FieldID, field.TypeUUID))
	if ps := tfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tfd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tfd.mutation.done = true
	return affected, err
}

// TestFeedDeleteOne is the builder for deleting a single TestFeed entity.
type TestFeedDeleteOne struct {
	tfd *TestFeedDelete
}

// Where appends a list predicates to the TestFeedDelete builder.
func (tfdo *TestFeedDeleteOne) Where(ps ...predicate.TestFeed) *TestFeedDeleteOne {
	tfdo.tfd.mutation.Where(ps...)
	return tfdo
}

// Exec executes the deletion query.
func (tfdo *TestFeedDeleteOne) Exec(ctx context.Context) error {
	n, err := tfdo.tfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{testfeed.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tfdo *TestFeedDeleteOne) ExecX(ctx context.Context) {
	if err := tfdo.Exec(ctx); err != nil {
		panic(err)
	}
}
