name: Docker

on:
  push:
    tags:
      - 'v*'

jobs:
  rss-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/itk13201/rss-generator
      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./docker/rss-generator/Dockerfile
          target: production
